---
your_name: "{{ lookup('env', 'USER') }}"
demo_region: us-east-2
demo_net_name: "{{ your_name }}-vpc"
demo_net: 192.168.1.0/24
demo_subnet: 192.168.1.0/26
demo_instance_type: t2.medium
# The recommended AMI to launch Amazone ECS container instances
demo_ami: "amzn-ami-*-amazon-ecs-optimized"
demo_profile_name: ecsInstanceRole
demo_sg: "{{ your_name }}-sg"
demo_hostname: "{{ your_name }}-vm"
demo_route_table: "{{ your_name }}-rt"
demo_repo: testrepo
demo_repo_tag: latest
demo_service: travis_test
demo_port: 5001
demo_user_data: |
  #cloud-config
  system_info:
    default_user:
      name: {{ your_name }}

  runcmd:
    - echo ECS_CLUSTER={{ cluster_name }} >> /etc/ecs/ecs.config
