---
- block:
  - name: Create a VPC
    ec2_vpc_net:
      name: "{{ demo_net_name }}"
      cidr_block: "{{ demo_net }}"
      region: "{{ demo_region }}"
      state: present
    register: vpc

  - name: Create a subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.vpc.id }}"
      cidr: "{{ demo_subnet }}"
      region: "{{ demo_region }}"
      state: present
    register: subnet

  - name: Connect the VPC to the Internet
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ demo_region }}"
    register: igw

  - name: Manage the VPC's route tables
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      subnets: "{{ subnet.subnet.id }}"
      region: "{{ demo_region }}"
      tags:
        Name: "{{ demo_route_table }}" # Give it a name so it won't be recreated.
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"

  when: action == "create"

- block:
  - name: Gather facts about the VPC
    ec2_vpc_net_facts:
      region: "{{ demo_region }}"
      filters:
        "tag:Name": "{{ demo_net_name }}"
    register: vpc_facts

  - name: Find the VPC's id
    set_fact:
      vpc_id: "{{ item.id }}"
    with_items: "{{ vpc_facts.vpcs }}"

  - name: Delete the subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc_id }}"
      cidr: "{{ demo_subnet }}"
      region: "{{ demo_region }}"
      state: absent

  - name: Delete the VPC Internet gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc_id }}"
      region: "{{ demo_region }}"
      state: absent

  - name: Gather facts about the security groups
    ec2_group_facts:
      region: "{{ demo_region }}"
      filters:
        vpc-id: "{{ vpc_id }}"
    register: sg_facts

  - name: Delete the security groups
    ec2_group:
      group_id: "{{ item.group_id }}"
      region: "{{ demo_region }}"
      state: absent
    with_items: "{{ sg_facts.security_groups }}"
    ignore_errors: yes
    no_log: true

  - name: Gather facts about the route tables
    ec2_vpc_route_table_facts:
      region: "{{ demo_region }}"
      filters:
        vpc-id: "{{ vpc_id }}"
    register: rt_facts

  - name: Delete the VPC's route tables
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_id }}"
      region: "{{ demo_region }}"
      lookup: id
      route_table_id: "{{ item.id }}"
      state: absent
    with_items: "{{ rt_facts.route_tables }}"
    ignore_errors: yes
    no_log: true

  - name: Delete the VPC
    ec2_vpc_net:
      region: "{{ demo_region }}"
      name: "{{ demo_net_name }}"
      cidr_block: "{{ demo_net }}"
      state: absent

  when: action == "destroy"
